# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Student.o StudentList.o
LINKOBJ  = main.o Student.o StudentList.o
LIBS     = -L"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/LTD/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -ansi
CFLAGS   = $(INCS) -ansi
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Student.o: Student.cpp
	$(CPP) -c Student.cpp -o Student.o $(CXXFLAGS)

StudentList.o: StudentList.cpp
	$(CPP) -c StudentList.cpp -o StudentList.o $(CXXFLAGS)
